"""
report.py — Renders eval.py's results as a static HTML page.

One self-contained file, no external assets, no JavaScript: open it in a
browser or send it as-is to a client. Regenerated by every eval.py run.
"""

import datetime
import html
from pathlib import Path

REPORT_OUT = Path(__file__).parent / "eval_report.html"


def _grade(pct: float) -> str:
    if pct >= 0.9:
        return "good"
    if pct >= 0.7:
        return "warn"
    return "bad"


def _cat_cell(r: dict) -> str:
    return f"{html.escape(r['expected_category'])} &rarr; {html.escape(str(r['predicted_category']))}"


def _esc_cell(r: dict) -> str:
    exp = "Escalate" if r["should_escalate"] else "Reply"
    got = "Escalate" if r["did_escalate"] else "Reply"
    return f"{exp} &rarr; {got}"


def write_html_report(rows: list[dict], model: str, cost: float) -> Path:
    n = len(rows)
    cat_right = sum(r["category_correct"] for r in rows)
    esc_right = sum(r["escalation_correct"] for r in rows)
    cat_pct = cat_right / n
    esc_pct = esc_right / n
    generated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    row_html = []
    for r in rows:
        passed = r["category_correct"] and r["escalation_correct"]
        row_html.append(f"""
        <tr class="{'pass' if passed else 'fail'}">
          <td class="id">{r['id']}</td>
          <td class="ticket">{html.escape(r['ticket'])}</td>
          <td class="{'ok' if r['category_correct'] else 'no'}">{_cat_cell(r)}</td>
          <td class="{'ok' if r['escalation_correct'] else 'no'}">{_esc_cell(r)}</td>
          <td class="badge {'pass' if passed else 'fail'}">{'&#10003;' if passed else '&#10007;'}</td>
        </tr>
        <tr class="detail-row">
          <td colspan="5">
            <details>
              <summary>Agent's final reply</summary>
              <p>{html.escape(r['final_message'])}</p>
            </details>
          </td>
        </tr>""")

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Flowdesk Triage Agent — Eval Results</title>
<style>
  :root {{
    --bg: #f7f7f8; --card: #ffffff; --text: #1c1c1f; --muted: #6b6b76;
    --border: #e4e4e8; --accent: #4f46e5;
    --good: #1a7f37; --warn: #9a6700; --bad: #c1121f;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 40px 24px; background: var(--bg); color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }}
  .wrap {{ max-width: 1000px; margin: 0 auto; }}
  h1 {{ font-size: 22px; margin: 0 0 4px; }}
  .subtitle {{ color: var(--muted); font-size: 14px; margin-bottom: 28px; }}
  .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-bottom: 28px; }}
  .card {{ background: var(--card); border: 1px solid var(--border); border-radius: 10px; padding: 16px; }}
  .card .label {{ font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: .04em; }}
  .card .value {{ font-size: 26px; font-weight: 600; margin-top: 4px; }}
  .card.good .value {{ color: var(--good); }}
  .card.warn .value {{ color: var(--warn); }}
  .card.bad .value {{ color: var(--bad); }}
  table {{ width: 100%; border-collapse: collapse; background: var(--card); border: 1px solid var(--border); border-radius: 10px; overflow: hidden; }}
  th, td {{ padding: 10px 12px; text-align: left; font-size: 13.5px; vertical-align: top; }}
  thead th {{ background: #fafafa; border-bottom: 1px solid var(--border); font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: var(--muted); }}
  tbody tr.pass, tbody tr.fail {{ border-top: 1px solid var(--border); }}
  td.id {{ color: var(--muted); width: 34px; }}
  td.ticket {{ max-width: 340px; }}
  td.ok {{ color: var(--good); }}
  td.no {{ color: var(--bad); font-weight: 600; }}
  .badge {{ text-align: center; font-weight: 700; width: 40px; }}
  .badge.pass {{ color: var(--good); }}
  .badge.fail {{ color: var(--bad); }}
  .detail-row td {{ padding: 0 12px 10px 12px; border-top: none; }}
  details summary {{ cursor: pointer; font-size: 12.5px; color: var(--accent); }}
  details p {{ font-size: 13px; color: var(--text); background: #fafafa; border: 1px solid var(--border); border-radius: 8px; padding: 10px 12px; margin: 8px 0 0; white-space: pre-wrap; }}
</style>
</head>
<body>
  <div class="wrap">
    <h1>Flowdesk Triage Agent — Eval Results</h1>
    <div class="subtitle">{n} tickets &middot; model: {html.escape(model)} &middot; generated {generated_at}</div>

    <div class="cards">
      <div class="card {_grade(cat_pct)}">
        <div class="label">Category accuracy</div>
        <div class="value">{cat_right}/{n} ({cat_pct:.0%})</div>
      </div>
      <div class="card {_grade(esc_pct)}">
        <div class="label">Escalation accuracy</div>
        <div class="value">{esc_right}/{n} ({esc_pct:.0%})</div>
      </div>
      <div class="card">
        <div class="label">Total cost</div>
        <div class="value">${cost:.3f}</div>
      </div>
      <div class="card">
        <div class="label">Cost per run</div>
        <div class="value">${cost / n:.4f}</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>ID</th><th>Ticket</th><th>Category (expected &rarr; actual)</th>
          <th>Escalation (expected &rarr; actual)</th><th>Pass</th>
        </tr>
      </thead>
      <tbody>
        {''.join(row_html)}
      </tbody>
    </table>
  </div>
</body>
</html>"""

    REPORT_OUT.write_text(page)
    return REPORT_OUT
